# -*- coding: utf-8 -*-
"""Notebook 7-actualizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sKwURktTIC6Yljzp7wK7R-IgU90SskS

### 🤖 Guía de Asistencia con IA: Consultas y Manipulación en Pandas

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Filtrados complejos**: Pandas es potente pero su sintaxis de indexación lógica puede ser confusa. Prueba con: *'Escribe una consulta en Pandas para filtrar las filas donde la columna A sea mayor que X y la columna B contenga el string Y'*.
- **Optimizar operaciones**: Si tienes un bucle para procesar un DataFrame, pregúntale: *'¿Cómo puedo vectorizar esta operación en Pandas para no usar un bucle?'*.

## Programa Ingenias+ Data Science

# Sección nueva

## Trabajando con Pandas

1) Importa las librerias requeridas: `Pandas` y `NumPy`.  

Una buena practica a la hora de escribir codigo es de comentar siempre que estoy haciendo (usando `#`) en la linea anterior. Por mas obvio que parezca lo que voy a hacer, puede ser que tenga que compartir el documento con otras personas y no sepan que quise hacer en cada linea. O que yo mismo lea el codigo tiempo despues y no recuerde porque lo hice.
"""

import pandas as pd
import numpy as np

"""2) Lee el archivo csv `life_expectancy_data` usando `pandas`. Guardalo en una variable llamada `expvida`."""

from google.colab import drive
drive.mount('/content/drive')

expvida = pd.read_csv('/content/drive/MyDrive/life_expectancy_data.csv')

expvida

"""[texto del vínculo](https:// [texto del vínculo](https://))3) ¿Que tipo de estructura de datos contiene la variable `expvida`?"""

# Obtengo el tipo de estructura de datos
type(expvida)

"""4) ¿Cuantas filas y columnas tiene `expvida`?"""

# Uso .shape para obtener cantidad de filas y columnas
expvida.shape

"""**Numero de filas**:

2938

**Numero de columnas**:

22

5) ¿Cual es el nombre de las columnas contenidas en `expvida`?
"""

# Obtengo el nombre de las columnas
expvida.columns

"""6) Inspecciona las primeras 10 filas de `expvida`"""

# Inspecciono las primeras filas
expvida.head(10)

"""7) Y ahora las 10 ultimas."""

# Inspecciono las ultimas filas
expvida.tail(10)

"""8) ¿Que tipos de datos contiene cada una de las columnas de `expvida`?"""

# Tipo de datos en cada columna
expvida.dtypes

"""9) ¿Hay valores faltantes en alguna de las columnas de `expvida`?"""

# Obtengo la cantidad de datos faltantes en cada columna
datos_faltantes = expvida.isnull().sum()
print(datos_faltantes)

"""10) Selecciona el maximo de datos faltantes. Calcula que porcentaje de los datos representan los datos faltantes."""

# Obtengo el maximo valor de datos faltantes y lo guardo en la variable masnan
masnan = expvida.isnull().sum().max()

print(f"El valor máximo de datos faltantes es {masnan}")

# Obtengo la cantidad de filas total y divido el maximo valor de datos faltantes por este numero
# y lo multiplico por 100

filas_total= len(expvida)

resultado1 = (masnan / filas_total) * 100

print(resultado1)

# Imprimo el maximo porcentaje de datos faltantes. Uso f-strings.

print(f"El porcentaje máximo de filas nulas es igual a {resultado1:.2f} %")

por_str = str(resultado1)

type(resultado1)

type(por_str)

print(type(por_str))

# Imprimo el maximo porcentaje de datos faltantes. Uso f-strings.

print(f"El porcentaje máximo de filas nulas es igual a {resultado1:.2f} %")

# Asigno el valor resultado1 al porcentaje
porcentaje = resultado1

por_str = str(porcentaje)

type(porcentaje)

type(por_str)

print(type(por_str))

"""- str.format()
- Template Class
- f-strings

#### Ahora vamos a realizar algunos calculos y manipulaciones sobre las columnas.

> Agregar bloque entrecomillado

Una función útil para este fin es: `.rename()`. Y podemos utilizarla de la siguiente manera: Si `df` es mi DataFrame y quiero renombrar la columna `columna` como `columna1`, y la columna `columna2` como `columna3`, utilizo la siguiente sintaxis:
  
`df.rename(columns={"columna": "columna1", "columna2": "columna3"}, inplace=True)`

11) Renombra la columna 'Life expectancy ' como 'life_expectancy', ' BMI ' como 'bmi' y ''Measles ' como 'measles'. No olvides de usar `inplace` para modificar el DataFrame original. Luego chequea que el cambio se haya hecho correctamente.
"""

# Renombro columnas del DataFrame
expvida = expvida.rename(columns={"Life expectancy ": "life_expectancy", " BMI ": "bmi", "Measles ": "measles"})

# Chequeo que se hayan reemplazado correctamente

"""12) ¿Cual es el promedio de expectativa de vida (Life expectancy) en general?"""

# Obtengo el promedio de la columna
expvida['life_expectancy'].mean()

"""13) ¿Cual es el promedio de expectativa de vida (Life expectancy) por país?"""

# Obtengo el promedio por pais
expvida.groupby('Country')['life_expectancy'].mean()

"""14) ¿Cual es la expectativa de vida mas alta y mas baja? Usa la funcion de pandas y la funcion de NumPy y compara el resultado. ¿Que paises tienen esas expectativas de vida?"""

# Maxima expectativa de vida usando numpy
#maxima = np.array(expvida['life_expectancy'])
#maxim_exp = np.max(array)

maxima = np.array(expvida['life_expectancy'])
maxim_exp = np.max(expvida['life_expectancy'])
print(maxim_exp)

# Maxima expectativa de vida usando pandas
maxima_exp = expvida['life_expectancy'].max()
print(maxima_exp)

# Minima expectativa de vida usando numpy
minima = np.array(expvida['life_expectancy'])
minim_exp = np.min(expvida['life_expectancy'])
print(minim_exp)

# Minima expectativa de vida usando pandas
minima_exp = expvida['life_expectancy'].min()
print(minima_exp)

# Muestro los resultados maximos
fila_maxima = expvida.loc[expvida['Country'].idxmax()]
print(f"La fila con el valor máximo es: {fila_maxima}")

# Muestro los resultados minimos
print(minima_exp)

# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al maximo
expvida.loc[expvida['life_expectancy'] == maxima_exp]

# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al minimo
expvida.loc[expvida['life_expectancy'] == minima_exp]

"""\15) ¿Cuantas categorias encontramos en la columna "Status"? _**Pista**_: Lee acerca de la función [unique()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html?highlight=unique#pandas.Series.unique)"""

# Obtengo los valores unicos de la columna status
valores_unicos = expvida['Status'].unique()
print(valores_unicos)

"""16) ¿Cuantos paises se ubican en cada una de esas categorias de "Status"? _**Pista**_: Lee acerca de la función [value_counts()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)




"""

# Cuento cuantos valores hay de cada categoria
expvida.groupby('Status')['Country'].value_counts()

"""18) ¿Cuantos paises presentaron algun caso de Sarampion (**Measles**) en el 2015? **_Pista_**: Lee acerca de la función [.count()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.count.html?highlight=count#pandas.DataFrame.count)"""

paisesSarampion=expvida[(expvida['Year'] == 2015)].count()
print(" el numero de paise que sufieron sarampion es",paisesSarampion['Country'])

# Cuento cuantas filas tienen valores distintos de cero
cantidad_filas = (expvida['measles'] != 0).sum()
print(cantidad_filas)