# -*- coding: utf-8 -*-
"""notebook-6-actualizado-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/martinieto12/ee19a890793b3d20575445ca3c96e8a9/notebook-6-actualizado-2.ipynb

### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.

# Programa Ingenias+ en Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Pandas`.

Antes de comenzar, vamos a hablar un poco de esta libreria.

**Pandas** es una libreria que es una extensión de NumPy. Basicamente al utilizar `pandas`, utilizo `numpy` por debajo. Esta orientada a la manipulación y análisis de datos debido a que ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales.

La estructura principal de `pandas` es el `DataFrame` que es muy similar a una tabla. Así también, contiene otra estrucutra denominada `Serie`.

Al ser de código abierto, `pandas` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion Pandas](https://pandas.pydata.org/pandas-docs/stable/)

## Clase 5: Pandas

Pandas es una gran ayuda para manejar nuestros dataset. En la clase de hoy, veremos algunos conceptos basicos de pandas y como leer datasets.
"""

#importa numpy
import numpy as np
#importa pandas
import pandas as pd
#importa maptoplib
import matplotlib.pyplot as plt

zanahoria = pd.Series(data = [1,2,3, 4, 6.7],
          index=['primero', 'segundo' ,'tercero', 'cuarto', 'quinto'])

type(zanahoria)



zanahoria

zanahoria['tercero']

zanahoria

# Para si un objeto tiene una columna, lo que hacemos es guardar
# en una variable
espejo = pd.DataFrame(data = [1,"rosa",3, 4, 6.7],
          index=['primero', 'segundo' ,'tercero','cuarto',  'quinto'])
# Cuando creamos una variable tipo dataframe,
# debo tener la misma cantidad de datos que de indices

espejo.index

espejo.index

espejo.columns # metodo columna stop=1 una sola columna

"""Pandas nos facilita con varias funciones para leer archivos. Entre ellas podemos encontrar:

- `.read_csv()`: lee archivos `csv` como DataFrame
- `.read_json()`: lee archivos `json` como DataFrame
- `.read_excel()`: leer archivos `excel` como DataFrame

Para conocer más funciones que ayuden a leer archivos, consulta [acá](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

Nosotras vamos a usar [`.read_csv()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

Los archivos `csv` son un tipo de documento en formato abierto sencillo para representar datos en forma de tabla, en las que las columnas se separan por comas (o punto y coma) y las filas por saltos de línea. Es uno de los formatos más utilizados en Data Science.

La sintaxis para poder leer un archivo csv es:
    
`df = pd.read_csv('nombredelarchivo.csv', delimiter=',')`

Aunque muchas veces se omite el `delimiter` si el archivo esta separado por comas.

Vamos a trabajar con el archivo `StudentsPerformance.csv`. Es usual descargar el archivo `csv` en la misma carpeta en la que trabajas con el jupyter notebook. De esta manera, no tendras que especificar el path a tu archivo.

1) Lee el archivo csv `StudentsPerformace` usando `pandas`. Guardalo en una variable llamada `students`.
"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/StudentsPerformance.csv')

"""# Nueva sección"""

# @title parental level of education

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('parental level of education').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

df.index

df.columns

"""2) ¿Que tipo de estructura de datos contiene la variable `students`? _Hint_: Usa `type`"""

type(df)

"""3) ¿Cuantas filas y columnas tiene `students`? Para contestar esta pregunta, pandas tiene la funcion `.shape()`. Su sintaxis es la siguiente: `df.shape()` (`df` debe ser reemplazado por el nombre de tu `DataFrame`).


De ahora en más cuando nos refiramos a un tipo de sintaxis donde debe colocarse `nombre_del_data_frame.funcion()`, la mencionaremos como `.funcion()`.

¿Que devuelve esta funcion? ¿Cual crees que corresponde a las filas y cual a las columnas?

**Numero de filas**: 1000

**Numero de columnas**: 9
"""

df.shape

"""3) ¿Cual es el nombre de las columnas contenidas en `students`? Para esto, pandas tiene el atributo `.columns`."""

df.columns

"""4) Inspecciona las primeras 10 filas de `students` usando la función `.head()`. Dentro de esta función podemos colocar un numero. Este numero nos dira cuantas filas queremos observar."""

df.head()

"""5) Ahora inspecciona las 10 ultimas usando `.tail()`. También podemos indicar el número de filas que queremos observar."""

df.tail(7)

"""6) ¿Que tipos de datos contiene cada una de las columnas de `students`? Para esto, utiliza el atributo `.dtypes`."""

df.dtypes

"""7) ¿Como accedemos a una fila o a una columa de un DataFrame?

Una de las maneras de acceder a una columna es especificando el nombre de la misma. Por ejemplo, `df['nombre_columna']`.

- Accede a la columna `gender` de `students`.
"""

df['gender']

df.gender

"""- Accede ahora a la columna `lunch`."""

df['lunch']

df.lunch

"""Otra manera de acceder es usando dos funciones `.loc[]` y `.iloc[]`.

- `iloc[1:m, 1:n]`: Se usa para seleccionar filas basadas en su posición de 1 a m filas y de 1 a n columnas.
"""

#seleccionar las dos primeras filas
df.iloc[:2, :9]

#o tambien se usa
df.iloc[:5,]

df.iloc[2,-2]

#Selecciona los datos entre la decima y vigesima fila.
df.iloc[10:21]

#Selecciona las dos primeras columnas
df.iloc[:, :2]

"""- `.loc[[nombre_fila], [nombre_columna]]`. Se usa para seleccionar filas o columnas basadas en su nombre"""

#Selecciona la fila por nombre 1, o sea con indice igual a 1
df.loc[1]

#Corre el codigo y observa que devuelve
df.loc[[1,20,3,4,5],['gender','lunch']]

#Selecciona las filas con indices 3, 10, 30, 43, 52 y columnas reading score y writing score
df.loc[[3, 10, 30, 43, 52], ['reading score', 'writing score']]

df2 = pd.DataFrame(data = ['perro', 'gato', 'flor'], index = ['str1', 'str2', 'st32'], columns=['titulo'])

df2

df2.loc['str1']

df2.iloc[1]

"""8) A veces queremos seleccionar filas que cumplan con ciertas condiciones, donde el valor de una columna en esa fila sea igual, mayor o menor que un valor.

Para esto tenemos que usar una sintaxis especial. Vamos a construirla de a poco. Imaginemos que tenemos un DataFrame `df` con las columnas `col1`, `col2` y `col3`. Queremos seleccionar solo aquellas filas donde `col1` sea mayor a 10.

Para eso diremos que queremos

df['col1'] > 10 (La columna col1 debe ser mayor a 10).
Ahora si corremos este codigo, veremos que devuelve valores booleanos. O sea devolvera False para aquellos valores que sean menores o iguales a 10 y True para los que sean mayores a 10.

O sea que tenemos que agregar algo mas para poder seleccionar las columnas. Esta lista de valores booleanos se llama mascara booleana.

¿Que significa? Que si yo le paso estos valores a pandas, pandas interpretara que debe conservar aquellos valores donde tiene True y descartar donde tiene False.

Por eso, para filtrar filas en base a estas condiciones escribimos:

df[df['col1] > 10].

Esto significa primero fijate en que filas de `df`, la columna `col1` es mayor a 10. Luego, selecciona solo aquellas filas donde esta condicion sea `True`.
"""

ejemplo = pd.DataFrame(data = [100,2,3, 4, 15,34],
          index=[1,2,3,4,5,6], columns=["col1"])

ejemplo

ejemplo['col1']>10

ejemplo[ejemplo['col1']>10]

#Selecciona solo las filas donde math score sea mayor a 70
df[df['math score']>7.0]

#Selecciona solo las filas donde reading score sea menor a 60

df[df['reading score']<60]

#Selecciona solo las filas donde gender sea igual a female
df[df['gender']=='female']

#Selecciona solo aquellas filas donde lunch sea distinto a standardisnull

df[df['lunch']!='standard']

#Muestra los valores de writing score para aquellos estudiantes que tengan reading score mayor a math score

df[df['reading score']>df['math score']]['writing score']

df[(df['reading score']>70) & (df['writing score']>70)]

"""9) Los valores faltantes son un problema muy grande a la hora de visualizar y limpiar datos así como también a la hora de entrenar un modelo. Uno de los pasos obligados de cualquier exploración de datos es evaluar la presencia de estos valores.

Como manejar estos datos faltantes es un gran desafio. La mayoría de las veces no queremos eliminar esos valores porque significaría perder información valiosa en otros features. En la proxima clase veremos como podemos manejarlos.

Los valores faltantes estan codificados normalemente como `NaN`. Esto no es un string, sino que es un valor especial de `NumPy` que es tratado como un flotante.

Para chequear si tenemos valores faltantes podemos usar la función `.isnull()`. Esto nos devuelve una nueva DataFrame en la cual tendremos el valor False si no es faltante y True si ese valor es faltante.
"""

#Usa .isnull() para ver que ocurre
new_df = pd.DataFrame({
    'nombre': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry', 'Iris', 'Jack'],
    'edad': [25, 30, np.nan, 28, 35, np.nan, 22, 29, 31, 26],
    'ciudad': ['Madrid', 'Asturias', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', np.nan, 'Málaga', 'Zaragoza', 'Palma'],
    'salario': [45000, 52000, 48000, np.nan, 61000, 55000, 50000, np.nan, 59000, 47000],
    'experiencia': [2, np.nan, 5, 3, 8, np.nan, 1, 4, 6, 2]
})
new_df

new_df.isnull()

"""Podemos sin embargo combinar esta función con otras para poder obtener el numero total de datos faltantes. Por ejemplo, podemos usar `.isnull().sum()`."""

#Prueba usar .isnull().sum() sobre tu dataframe para ver que devuelve
new_df.isnull().sum()

"""```
# Esto tiene formato de código
```

¿Hay valores faltantes en alguna de las columnas de `students`? ____

10) Si la cantidad de valores faltantes es poca, podemos entonces deshacernos de ellas. Para esto pandas ofrece la función [`.dropna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html). Esta función hara que se eliminen las filas donde hay valores faltantes. Si no le pasamos ningun parametro extra, eliminara todas las filas con valores faltantes. Sin embargo, podes chequear en la documentación como eliminar solo algunas de las filas.
"""

#Elimina todas las filas que tengan valores faltantes. No te olvides de poner inplace=True dentro de la función.
df.dropna(inplace=True)
new_df.dropna(inplace=True)
new_df

"""12) Una manera de ver facilmente algunos detalles estadisticos de cada columna de un DataFrame es usando la fución `.describe()`."""

#Usa la funcion .describe() sobre students y describe que informacion estadistica proporciona
df.describe()

"""Tambien es posible visualizar, por ejemplo, el promedio de una columna. Para esto pandas usa la función de numpy, pero provee la misma sintaxis que las demás funciones. Por ejemplo, si queremos calcular el promedio de la columna `col1` del DataFrame `df` usamos `df['col1'].mean()`."""

#Calcula el promedio de la columna math score de students
df['math score'].mean()

"""También podemos usar funciones como `.min()`, `.max()`, `.median()`, `.std()`."""

#Calcula el minimo y maximo valor, la mediana y el desvio estandard en la columna math score de students
df['math score'].min()

df['math score'].max()

df['math score'].median()

df['math score'].std()

"""14) [Investiga](https://pandas.pydata.org/pandas-docs/stable/index.html) y trata de aplicar las siguientes funciones de `pandas`:

```

- `.index`
"""

new_df = pd.DataFrame({
    'nombre': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry', 'Iris', 'Jack'],
    'edad': [25, 30, np.nan, 28, 35, np.nan, 22, 29, 31, 26],
    'ciudad': ['Madrid', np.nan, 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', np.nan, 'Málaga', 'Zaragoza', 'Palma'],
    'salario': [45000, 52000, 48000, np.nan, 61000, 55000, 50000, np.nan, 59000, 47000],
    'experiencia': [2, np.nan, 5, 3, 8, np.nan, 1, 4, 6, 2]
})
new_df

new_df.index

"""- `.drop()`

```
# Esto tiene formato de código
```
"""

new_df.drop(columns=['nombre'], inplace=True)
new_df

"""- `.groupby()`"""

df.groupby('gender').mean(numeric_only=True)

df.groupby('lunch').mean(numeric_only=True)

"""- `.fillna()`"""

new_df.fillna(0)

"""- `.rename()`"""

new_df.rename(columns={'ciudad':'lugar'}, inplace=True)

"""- `.astype()`"""

new_df.astype({'edad':'float'})

"""- `.unique()`"""

# Using .unique() on the 'lugar' column (which was previously 'ciudad') to see unique city names
new_df['lugar'].unique()

"""- `.value_counts()`"""

df['test preparation course'].value_counts()

"""- `.count()`

### `.count()`

La función `.count()` se usa para obtener el número de valores no nulos en cada columna de un DataFrame o en una Serie. Es útil para verificar cuántas entradas válidas tienes en cada característica de tus datos.
"""

# Usando .count() en new_df para ver el número de valores no nulos en cada columna
print("Conteo de valores no nulos en new_df:\n", new_df.count())

"""- `.reset_index()`

### `.reset_index()`

La función `.reset_index()` se utiliza para restablecer el índice de un DataFrame o Serie. Mueve el índice actual a una columna regular (o lo descarta si `drop=True`) y establece un nuevo índice numérico predeterminado (de 0 a N-1). Es muy útil después de operaciones como `groupby()` que pueden generar un MultiIndex o un índice no secuencial.
"""

# Primero, creamos un DataFrame de ejemplo con un índice personalizado para demostrar .reset_index()
example_df = pd.DataFrame({'value': [10, 20, 30]}, index=['A', 'B', 'C'])
print("DataFrame original:\n", example_df)

# Usamos .reset_index() para mover el índice 'A', 'B', 'C' a una columna
reset_df = example_df.reset_index()
print("\nDataFrame después de .reset_index():\n", reset_df)

# También podemos usar drop=True si no queremos que el índice anterior se convierta en una columna
reset_df_dropped = example_df.reset_index(drop=True)
print("\nDataFrame después de .reset_index(drop=True):\n", reset_df_dropped)